### ISSUE TITLE
Kanban Board - Capstone Rails/ React

### ISSUE THREAD

**Issue by Rebelzob** [Rysth/RAILS-AppointWheels#17]
### Appoint Wheels

- 💻 Link to the project [here](https://github.com/users/Rysth/projects/2)
-  🌟There are 4 people on our team
    - @Rebelzob 
    - @SnakyMz 
    - @Rysth 
    - @IsmaelMastronardi 
- 📅 Kanban Board Screenshot

![image](https://github.com/Rysth/RAILS-AppointWheels/assets/52711805/ca7f2756-208e-4fe5-ab64-ffbdfb9271c1)

**Comment by Meltrust** [comment]
## Wow, you did it 🎉 
![Brilliant](https://media.giphy.com/media/d31w24psGYeekCZy/giphy.gif)

Your project is complete!  :shipit: 
Congratulations! 🎉 

### To highlight

- All cards have descriptions, assignees, and pointings according to spec✔️ 


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
